base: ghcr.io/vanilla-os/pico:main
name: Vanilla Core
singlelayer: false
labels:
  maintainer: Vanilla OS Contributors
args:
  DEBIAN_FRONTEND: noninteractive
runs:
- echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

modules:
- name: mandb
  type: shell
  commands:
  - apt update
  - apt install -y man-db
  - mandb -c

- name: fsguard
  type: shell
  source:
    type: tar
    url: https://github.com/linux-immutability-tools/FsGuard/releases/download/v0.1.2/FsGuard_0.1.2_linux_amd64.tar.gz
  commands:
  - apt install -y minisign
  - mv /sources/FsGuard /usr/bin
  - /usr/bin/gen_fsguard_filelist /usr/bin
  - sed -i '\/usr\/bin\/gen_fsguard_filelist.*/d' /FsGuard/filelist
  - sed -i '\/usr\/bin\/sign_filelist.*/d' /FsGuard/filelist
  - /usr/bin/sign_filelist

- name: packages-modules
  type: includes
  includes:
    - modules/00-vanilla-abroot
    - modules/00-vanilla-base-files
    - modules/00-vanilla-apx
    - modules/00-vanilla-apx-stacks
    - modules/00-vanilla-ikaros
    - modules/05-firmware
    - modules/10-input-and-locale
    - modules/20-ssh
    - modules/30-utils
    - modules/40-essentials
    - modules/50-fs
    - modules/60-sound
    - modules/70-compression
    - modules/80-xdg
    - modules/90-network
    - modules/100-modules
    - modules/110-fwupd
    - modules/120-fingerprint
    - modules/130-kernel
    - modules/140-manpages
    - modules/999-replace-locale-gen

- name: cleanup
  type: shell
  commands:
  - apt remove -y linux-image-rt-amd64 linux-image-6.4.0-4-rt-amd64
  - apt remove -y dpkg-dev build-essential
  - apt autoremove -y
  - apt clean
  - rm -rf /var/cache/*
  - rm -rf /tmp/*
  - rm -rf /var/tmp/*
  - rm -rf /sources
  - rm /usr/bin/gen_fsguard_filelist
  - rm /usr/bin/sign_filelist
  - mkdir -p /var/cache/apt/archives/partial
