#!/bin/sh

PREREQ="lvm2"

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/sbin/pdata_tools /usr/sbin
ln -s /usr/sbin/pdata_tools ${DESTDIR}/usr/sbin/thin_repair
